name: work_on_v1
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  auto_size_text: 3.0.0
  barcode_widget: 2.0.3
  cached_network_image: 3.4.1
  cached_network_image_platform_interface: 4.1.1
  cached_network_image_web: 1.3.1
  collection: 1.19.1
  csslib: 1.0.2
  dropdown_button2: 2.3.9
  expandable: 5.0.1
  file_picker: 10.1.9
  fl_chart: 1.0.0
  flutter_animate: 4.5.0
  flutter_cache_manager: 3.4.1
  flutter_native_splash: 2.4.1
  flutter_plugin_android_lifecycle: 2.0.28
  flutter_rating_bar: 4.0.1
  flutter_staggered_grid_view: 0.7.0
  flutter_svg: 2.1.0
  font_awesome_flutter: 10.7.0
  from_css_color: 2.0.0
  go_router: 12.1.3
  google_fonts: 6.1.0
  geolocator: ^13.0.2
  google_maps_flutter: ^2.5.3
  html: 0.15.6
  image_picker: 1.1.2
  image_picker_android: 0.8.12+23
  image_picker_for_web: 3.0.6
  image_picker_ios: 0.8.12+2
  image_picker_linux: 0.2.1+2
  image_picker_macos: 0.2.1+2
  image_picker_platform_interface: 2.10.1
  image_picker_windows: 0.2.1+1
  intl: 0.20.2
  json_path: 0.7.2
  lottie: 3.1.2
  mask_text_input_formatter: 2.9.0
  mime_type: 1.0.0
  page_transition: 2.1.0
  path_provider: 2.1.4
  path_provider_android: 2.2.10
  path_provider_foundation: 2.4.0
  path_provider_linux: 2.2.1
  path_provider_platform_interface: 2.1.2
  path_provider_windows: 2.3.0
  percent_indicator: 4.2.2
  photo_view: 0.15.0
  pin_code_fields: 8.0.1
  plugin_platform_interface: 2.1.8
  provider: 6.1.5
  shared_preferences: 2.5.3
  shared_preferences_android: 2.4.10
  shared_preferences_foundation: 2.5.4
  shared_preferences_linux: 2.4.1
  shared_preferences_platform_interface: 2.4.1
  shared_preferences_web: 2.4.3
  shared_preferences_windows: 2.4.1
  share_plus: ^10.1.4
  smooth_page_indicator: 1.1.0
  sqflite: 2.3.3+1
  sqflite_common: 2.5.4+3
  table_calendar: 3.2.0
  timeago: 3.7.1
  universal_io: 2.2.2
  url_launcher: 6.3.1
  url_launcher_android: 6.3.16
  url_launcher_ios: 6.3.3
  url_launcher_linux: 3.2.1
  url_launcher_macos: 3.2.2
  url_launcher_platform_interface: 2.3.2
  url_launcher_web: 2.4.1
  url_launcher_windows: 3.1.4
  video_player: 2.10.0
  video_player_android: 2.8.7
  video_player_avfoundation: 2.7.1
  video_player_platform_interface: 6.3.0
  video_player_web: 2.3.5
  xml: 6.5.0

  # PR-5: Stripe Payment Sheet
  flutter_stripe: ^11.4.0

  # PR-F26: Firebase Cloud Messaging
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.6

  # Discovery Feature: Swipe cards
  flutter_card_swiper: ^7.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dependency_overrides:
  http: 1.4.0
  uuid: ^4.0.0

dev_dependencies:
  flutter_launcher_icons: 0.13.1
  flutter_lints: 4.0.0
  image: 4.2.0
  lints: 4.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4


# ═══════════════════════════════════════════════════════════════════════════
# WorkOn App Icon Configuration
# Design: Red phone icon on dark background (#0D0D0F)
# Brand Color: #E53935 (WorkOn Red)
# ═══════════════════════════════════════════════════════════════════════════
flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
  # Main icon (will be generated from PNG export of SVG)
  image_path: 'assets/icons/app_icon_1024.png'
  # Android Adaptive Icon (Android 8+)
  adaptive_icon_background: '#0D0D0F'  # WorkOn Dark
  adaptive_icon_foreground: 'assets/icons/app_icon_foreground.png'
  min_sdk_android: 21
  remove_alpha_ios: true  # Required by Apple

# ═══════════════════════════════════════════════════════════════════════════
# WorkOn Splash Screen Configuration
# Dark theme for premium feel, red accent
# ═══════════════════════════════════════════════════════════════════════════
flutter_native_splash:
  color: "#0D0D0F"  # Dark mode primary
  image: assets/images/workon_splash_logo.png
  color_dark: "#0D0D0F"
  image_dark: assets/images/workon_splash_logo.png
  android: true
  ios: true
  web: true
  android_12:
    color: "#0D0D0F"
    icon_background_color: "#0D0D0F"
    image: assets/images/workon_splash_logo.png
    color_dark: "#0D0D0F"
    icon_background_color_dark: "#0D0D0F"
    image_dark: assets/images/workon_splash_logo.png

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/

  fonts:
    - family: 'General Sans'
      fonts:
        - asset: assets/fonts/GeneralSans-Extralight.otf
          weight: 200
        - asset: assets/fonts/GeneralSans-ExtralightItalic.otf
          weight: 200
          style: italic
        - asset: assets/fonts/GeneralSans-Light.otf
          weight: 300
        - asset: assets/fonts/GeneralSans-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/GeneralSans-Regular.otf
        - asset: assets/fonts/GeneralSans-Italic.otf
          style: italic
        - asset: assets/fonts/GeneralSans-Medium.otf
          weight: 500
        - asset: assets/fonts/GeneralSans-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/GeneralSans-Semibold.otf
          weight: 600
        - asset: assets/fonts/GeneralSans-SemiboldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/GeneralSans-Bold.otf
          weight: 700
        - asset: assets/fonts/GeneralSans-BoldItalic.otf
          weight: 700
          style: italic

    - family: MigambiIconOutline
      fonts:
        - asset: assets/fonts/Migambi--Icon--Outline.ttf
    - family: MigambiVIPIcons
      fonts:
        - asset: assets/fonts/Migambi-VIP-Icons.ttf


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

